### ISSUE TITLE
Underline / strikethrough in PDF

### ISSUE THREAD

**Issue by Axel-Naumann** [mpark/wg21#19]
The PDF output does not show add/rm as underline / strikethrough. This is an issue for CWG. #18 makes me prefer PDF, were it not for the lack of underline / strikethrough...

**Comment by mpark** [comment]
I did look into adding underline/strikethrough in PDF but LaTeX support for them is pretty poor. I can say that #18 will be easier for me to fix.

**Comment by mpark** [comment]
This comment is a bit late, but this issue was fixed such that spans get underline / strikethrough, but divs do not. Examples:
![span](https://user-images.githubusercontent.com/2275240/57831104-0fb06280-7769-11e9-969f-43cc39e032fe.jpeg)
![div](https://user-images.githubusercontent.com/2275240/57831106-1212bc80-7769-11e9-9638-1dd9e928333e.jpeg)
